-- MySQL Script generated by MySQL Workbench
-- Wed May 27 10:25:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biblioteca` ;

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`estado` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`estado` (
  `idestado` INT NOT NULL,
  `dscNomeEstado` VARCHAR(45) NULL,
  `dscUFEstado` VARCHAR(45) NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`cidade` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`cidade` (
  `idcidade` INT NOT NULL,
  `idEstado` INT NOT NULL,
  `dscNomeCidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idcidade`),
  INDEX `fk_cidade_estado1_idx` (`idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `biblioteca`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`endereco` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`endereco` (
  `idendereco` INT NOT NULL,
  `idCidade` INT NOT NULL,
  `dscTipoLogradouroEnder` VARCHAR(45) NULL,
  `dscNomeLogradouroEnder` VARCHAR(45) NULL,
  `numNumeroEnder` VARCHAR(45) NULL,
  `dscComplementoEnder` VARCHAR(45) NULL,
  `dscBairroEnder` VARCHAR(45) NULL,
  `numCEPEnder` VARCHAR(45) NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_endereco_cidade1_idx` (`idCidade` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`idCidade`)
    REFERENCES `biblioteca`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`associado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`associado` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`associado` (
  `idAssoc` INT NOT NULL AUTO_INCREMENT,
  `idEnder` INT NOT NULL,
  `nomAssoc` VARCHAR(100) NOT NULL,
  `indSexAssoc` CHAR(1) NOT NULL,
  `dscEndAssoc` VARCHAR(200) NOT NULL,
  `dscTipAssoc` VARCHAR(10) NOT NULL DEFAULT 'comum',
  PRIMARY KEY (`idAssoc`, `idEnder`),
  INDEX `fk_associado_endereco1_idx` (`idEnder` ASC) VISIBLE,
  CONSTRAINT `fk_associado_endereco1`
    FOREIGN KEY (`idEnder`)
    REFERENCES `biblioteca`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`autor` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `nomAutor` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`editora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`editora` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`editora` (
  `idEdit` INT NOT NULL AUTO_INCREMENT,
  `dscEdit` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idEdit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`produto` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`produto` (
  `idProd` INT NOT NULL AUTO_INCREMENT,
  `dscTitProd` VARCHAR(150) NOT NULL,
  `valMultDiarProd` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `valVendProd` DECIMAL(10,2) NOT NULL,
  `dscTipProd` VARCHAR(20) NOT NULL,
  `dscFormProd` VARCHAR(20) NULL DEFAULT NULL,
  `idEdit` INT NOT NULL,
  PRIMARY KEY (`idProd`),
  INDEX `idc_Produto_Edit` (`idEdit` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Editora`
    FOREIGN KEY (`idEdit`)
    REFERENCES `biblioteca`.`editora` (`idEdit`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`exemplar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`exemplar` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`exemplar` (
  `idExemp` INT NOT NULL AUTO_INCREMENT,
  `idProd` INT NOT NULL,
  PRIMARY KEY (`idExemp`),
  INDEX `idc_Exemplar_Prod` (`idProd` ASC) VISIBLE,
  CONSTRAINT `fk_Exemplar_Produto`
    FOREIGN KEY (`idProd`)
    REFERENCES `biblioteca`.`produto` (`idProd`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`emprestimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`emprestimo` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`emprestimo` (
  `idEmpr` INT NOT NULL AUTO_INCREMENT,
  `idAssoc` INT NOT NULL,
  `idExemp` INT NOT NULL,
  `datRetEmpr` DATE NOT NULL,
  `datPrevEntrEmpr` DATE NOT NULL,
  `datEfetEntrEmpr` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idEmpr`),
  INDEX `idc_Emprestimo_Assoc` (`idAssoc` ASC) VISIBLE,
  INDEX `idc_Emprestimo_Exemp` (`idExemp` ASC) VISIBLE,
  CONSTRAINT `fk_Emprestimo_Associado`
    FOREIGN KEY (`idAssoc`)
    REFERENCES `biblioteca`.`associado` (`idAssoc`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Emprestimo_Exemplar`
    FOREIGN KEY (`idExemp`)
    REFERENCES `biblioteca`.`exemplar` (`idExemp`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`multa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`multa` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`multa` (
  `idMult` INT NOT NULL AUTO_INCREMENT,
  `idEmpr` INT NOT NULL,
  `dscTipMult` VARCHAR(15) NOT NULL,
  `valMult` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idMult`),
  INDEX `idc_Multa_Empr` (`idEmpr` ASC) VISIBLE,
  CONSTRAINT `fk_Multa_Emprestimo`
    FOREIGN KEY (`idEmpr`)
    REFERENCES `biblioteca`.`emprestimo` (`idEmpr`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`pagamento` (
  `idPagto` INT NOT NULL AUTO_INCREMENT,
  `idMult` INT NOT NULL,
  `valPagto` DECIMAL(10,2) NOT NULL,
  `dscFormPagto` VARCHAR(20) NOT NULL,
  `valDescPagto` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`idPagto`),
  UNIQUE INDEX `uq_Pagamento_Multa` (`idMult` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Multa`
    FOREIGN KEY (`idMult`)
    REFERENCES `biblioteca`.`multa` (`idMult`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`produtoautor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`produtoautor` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`produtoautor` (
  `idProd` INT NOT NULL,
  `idAutor` INT NOT NULL,
  PRIMARY KEY (`idProd`, `idAutor`),
  INDEX `idc_ProdutoAutor_Autor` (`idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_ProdutoAutor_Autor`
    FOREIGN KEY (`idAutor`)
    REFERENCES `biblioteca`.`autor` (`idAutor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ProdutoAutor_Produto`
    FOREIGN KEY (`idProd`)
    REFERENCES `biblioteca`.`produto` (`idProd`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
